server:
  port: 8082
  servlet:
    context-path: /

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
#  redis:
#    host: localhost
#    port: 6379
#    database: 1
#    timeout: 10000
#  rabbitmq:
#    #rabbitmq的ip
#    host: 192.168.227.130
#    username: admin
#    password: admin
#    #虚拟主机
#    virtual-host: /
#    #端口
#    port: 5672

logging:
  level:
    com.example: debug
    org.springframework: warn

sys:
  auth:
    exclude-paths:
      - /hello/**
      - /user/**
      - /role/**
      - /menu/**
      - /roleMenu/**
      - /roleMenuPermission/**
      - /permission/**
      - /idm/**
      - /school/**
      - /file/**
      - /images/**
      - /log/**
      - /viewHistory/**
      - /userFriend/**

springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.example.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true